title: PLUGIN_ADMIN.DEFAULT

rules:
  slug:
    pattern: '[a-zA-Zа-яA-Я0-9_\-]+'
    min: 1
    max: 200

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            header.published:
              type: toggle
              toggleable: true
              label: PLUGIN_ADMIN.PUBLISHED
              help: PLUGIN_ADMIN.PUBLISHED_HELP
              highlight: 1
              size: medium
              options:
                1: PLUGIN_ADMIN.YES
                0: PLUGIN_ADMIN.NO
              validate:
                type: bool

            header.title:
              type: text
              autofocus: true
              style: vertical
              label: Titre

            header.custom.caption:
              type: text
              label: Légende du projet

            header.date:
              type: datetime
              label: PLUGIN_ADMIN.DATE
              toggleable: true
              help: PLUGIN_ADMIN.DATE_HELP

            header.custom.type:
              type: text
              label: Type de projet
                      
            header.custom.list:
              type: section
              title: Diaporama
              text:  Télécharger ici les images dans leur ordre d'affichage sur la page. 
              underline: true
              fields:
                header.custom.images:
                  type: list
                  style: vertical

                  fields:
                    .image:
                      label: Image (JPG ou SVG, max 2Mo) – Exporter un jpg d'une largeur de 2500px  en 72dpi (qualité 10).
                      type: file
                      destination: 'self@'
                      multiple: false
                      accept:
                        - image/*
                    .alt:
                      label: Description de l'image pour le référencement et les mal-voyants (exemple – vue de la signalétique du Frac Sud)
                      type: Text
                    .video:
                      type: text
                      label: Vidéo – Lien de la vidéo vimeo ou youtube si seule (avec https:// ).
                    
            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA

        advanced:
          type: tab
          title: PLUGIN_ADMIN.ADVANCED

          fields:
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:

                    settings:
                      type: section
                      title: PLUGIN_ADMIN.SETTINGS
                      underline: true

                    folder:
                      type: text
                      label: PLUGIN_ADMIN.FOLDER_NAME
                      validate:
                        rule: slug

                    route:
                      type: parents
                      label: PLUGIN_ADMIN.PARENT
                      classes: fancy

                    name:
                      type: select
                      classes: fancy
                      label: PLUGIN_ADMIN.PAGE_FILE
                      help: PLUGIN_ADMIN.PAGE_FILE_HELP
                      default: default
                      data-options@: '\Grav\Common\Page\Pages::pageTypes'